feat: [] wistia-videos app
contentful/apps pull request #1622
Opened 2022-08-16 12:46 UTC by vikaskumr

2022-08-30 16:07 UTC, andipaetzold requested changes
Very rough review from me, will do a more thorough one tomorrow:

Can we please split the files into `locations` and `components` as we do in our template? For consistency.

Use emotion for global styles

2022-08-30 16:07 UTC, andipaetzold commented on apps/wistia-videos/package.json
> +    "styled-components": "^5.3.3"
Use emotion instead

2022-08-30 16:07 UTC, andipaetzold commented on apps/wistia-videos/package.json
> +    "@contentful/forma-36-react-components": "^3.100.7",
Do not use Forma v3, upgrade and use Forma v4

2022-08-30 16:07 UTC, andipaetzold commented on apps/wistia-videos/src/components/ConfigScreen.tsx
> +      console.log(`Connection to Wistia Data API failed: ${response.error}`);
Remove this line

2022-09-27 08:57 UTC, therrou requested changes

2022-09-27 08:57 UTC, therrou commented on apps/wistia-videos/src/components/Field.tsx
> +  const updateVideoIds = (id:any) => {
Could be possible to add to this function the parameters from the creation of the content model? Right now is possible to add unlimited videos even when we set in the content model a limit or just one.
 The same with the _required_, it is an empty array and is a required field that shouldn't be possible to publish the entry.

2022-12-28 12:09 UTC, closed without merging