Hacktag: Add Angular template to /examples
contentful/apps pull request #3332
Opened 2023-04-28 02:52 UTC by pkeavenycontentful

## Purpose

We've gotten feedback from prospective clients that more support for Angular would help with adoption of the Contentful system. Adding an angular example is a path to this. 

## Approach

## Testing steps

- cd into /examples/angular
- npm install
- ng serve
- verify the example serves successfully

2023-05-11 13:22 UTC, andipaetzold requested changes
- Does the final build work with app hosting?

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/angular-example/.angular/cache/15.2.6/angular-webpack/b5b0dc6bea5b3bba08918cc5f24bae87effb3b03/0.pack
This should probably be ignored

2023-05-11 13:22 UTC, andipaetzold commented on package.json
Revert this file

2023-05-11 13:22 UTC, andipaetzold commented on package-lock.json
Revert this file

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/src/app/AppConfigLocation/appConfigLocation.component.html
> +<div>
Why the nested `<div>`?  Can't we keep it clean and simply render `<p>Hello Config (AppId {{ sdk.ids.app }})</p>` which roughly matches what our TypeScript example does

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/package.json
> +  "dependencies": {
Can we pin all dependencies?

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/package.json
> +  "scripts": {
Please add the scripts from TypeScript example: https://github.com/contentful/apps/blob/be8304afc8cc52b89cfded06af6e405f7f004515/examples/typescript/package.json#L21-L23

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/src/favicon.ico
not needed - this is an iframe. Please also remove the `<link>` from index.html

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/src/app/LocalHostWarning/localHostWarning.component.ts
The capital H in `localhost` triggers me :D

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/src/app/app.component.ts
> +  @ViewChild(DynamicComponentDirective, { static: true })
Do you need a directive here? Feels overly complex. Shouldn't an element reference be fine?

2023-05-11 13:22 UTC, andipaetzold commented on examples/angular/README.md
> +# AngularExample
This should be aligned with existing readmes: https://github.com/contentful/apps/blob/master/examples/typescript/README.md

2023-06-22 18:58 UTC, jsdalton commented
Small note that we had an internal conversation on this PR and @mgoudy91 has agreed to shepherd this forward from here. 💪

2023-11-16 15:52 UTC, closed without merging

2023-11-16 15:54 UTC, mgoudy91 commented
Closing for now and if we need to revisit we can reference it