Feature/integ 622: Add AWS Build button to Sidebar Location
contentful/apps pull request #3710
Opened 2023-06-08 20:15 UTC by pkeavenycontentful

## Purpose

Content editors will need a way to trigger AWS Amplify builds from the sidebar. This PR adds the Build button to the sidebar location. 

## Approach
For testing purposes and to get around the CORS errors thrown from Amplify, I used [cors-anywhere](https://www.npmjs.com/package/cors-anywhere) to proxy the request from localhost to a CORS enabled server. This is meant only for development purposes. 

## Testing steps

- Create an AWS amplify app and point it to your localhost
- Go to any Content screen, verify Build button shows up in the sidebar
- Execute Build button, ensure appropriate error messaging occurs
- To test success messaging, follow instructions in the Readme to enable `cors-anywhere`

2023-06-09 14:59 UTC, ryunsong-contentful commented on apps/aws-amplify/src/locations/Sidebar.tsx
> +      'https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=7a31abcf-724e-4072-9329-8541f4e3bb02&token=Lba6wO2uyDKgDA6BmHcqUqXefzVZa9GG8r23HNQVuc';
An improvement here would be to place in this a .env file.

Even better yet, just have it call it from the parameters from the Config file using the Sidebar SDK - Matt will know how to do this if you ask him

2023-06-09 21:44 UTC, matthew-gordon approved these changes
LGTM ✅ , I think the files should clear up when https://github.com/contentful/apps/pull/3721 is merged 🤔 and rebase thise

2023-06-14 23:39 UTC, matthew-gordon requested changes
Lets look at this together after rebasing and updated the invocation logic, I think we can remove the `cors-anywhere` workaround and such 💪 #3721 is merged

2023-06-15 20:48 UTC, matthew-gordon commented on apps/aws-amplify/src/locations/Sidebar.tsx
> +    const webhookURL = 'https://sdlb4gygrnzr252nrx4h3tghym0fameu.lambda-url.us-west-2.on.aws/';
💪 nice! I know this probably a temp, maybe we shove move into an ENV var? Can do that as cleanup in a "final pass" fast follow with the other small things

2023-06-15 21:36 UTC, merged