Remove unused CONTENTFUL_HOST environment variable
contentful/apps pull request #9344
Opened 2024-12-17 18:16 UTC by twogood

## Purpose

Solve problem for Windows user that posted in Contentful Discord:

https://discord.com/channels/1030176999471321129/1317987388567457835

## Approach

Remove unused `CONTENTFUL_HOST` environment variable and `host` variable in http.ts.

If `CONTENTFUL_HOST` had been in use, using `cross-env` had been the way to go.

## Testing steps

User solved it this way themselves locally.

## Breaking Changes

No.

## Dependencies and/or References

No.

## Deployment

No, this is example code.

2024-12-17 22:10 UTC, Seth-Carter requested changes
Let's just leave it as is and go head and use `cross-env`.

2024-12-17 22:10 UTC, Seth-Carter commented on examples/native-external-references/package.json
> +    "create-resource-entities": "ts-node -T -r dotenv/config ./src/tools/create-resource-entities.ts",
```suggestion
    "create-resource-entities": "cross-env CONTENTFUL_HOST=api.contentful.com ts-node -T -r dotenv/config ./src/tools/create-resource-entities.ts",
```

2024-12-17 22:10 UTC, Seth-Carter commented on examples/native-external-references/package.json
> +    "show-resource-entities": "ts-node -T -r dotenv/config ./src/tools/show-resource-entities.ts"
```suggestion
    "show-resource-entities": "cross-env CONTENTFUL_HOST=api.contentful.com ts-node -T -r dotenv/config ./src/tools/show-resource-entities.ts"
```

2024-12-17 22:10 UTC, Seth-Carter commented on examples/native-external-references/src/tools/http.ts
```suggestion

const host = process.env.CONTENTFUL_HOST ?? 'api.contentful.com';

```

2024-12-18 18:52 UTC, twogood commented
> Let's just leave it as is and go head and use `cross-env`.

PR updated based on feedback. Commit history got weird though.

2024-12-18 20:19 UTC, useyourillusions commented
Hi!
Cross-env could be a great solution for cases where we truly need this environment variable, but it's entirely unusable within the source code. Wouldn't it make more sense to remove it?

2025-08-07 09:25 UTC, closed without merging